### ISSUE TITLE
grok_progressive_rad_damages.script calling on non-existent file

### ISSUE THREAD

**Issue by GodFlameTIC** [Paint-Thinner/Ladies-and-Sister-Stalkers-LASS#6]
The new BHS changed the file from blur2.ppe to blur_bhs.ppe. The script is currently calling on blur2.ppe, thus causing CTDs. Pls patch!

**Comment by StevenXHK** [comment]
> The new BHS changed the file from blur2.ppe to blur_bhs.ppe. The script is currently calling on blur2.ppe, thus causing CTDs. Pls patch!

Thanks for finding out the problematic script.
You can open grok_progressive_rad_damages.script can comment out the line referencing "blur_bhs.ppe" with "--"
